### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by sulljason** [kawaCat/MediaInfo-For-LuaJIT#1]
Could you please clarify what this is licensed under. I pointed it to a shared object and it worked. I want to use it instead of running the command 500 times and regexing it. Thank you! :D

**Comment by kawaCat** [comment]
Thank you for comment! and sorry my delayed reply.
the "MediaInfo-For-LuaJIT" in this repository is Free Lisence. its not have any limits.you can use this library feel free. ;)

and third party licenses.
* Mediainfo ( MediaInfo(Lib) License ) : ( https://mediaarea.net/en/MediaInfo/License )
* LuaJit ( Mit License) :  ( http://luajit.org/luajit.html )

Thanks again! :)
